### INICIAR SESION
POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email": "nuwa10@gmail.com",
    "password": "123123"
}

### REGISTRARSE
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "name": "fazt101",
    "email": "fazt101@gmail.com",
    "password": "fazt101"
}

### CERRAR SESIÓN
POST http://localhost:3000/api/signout

### PERFIL DE USUARIO
GET http://localhost:3000/api/profile
Content-Type: application/json

{
    "name": "marcoss",
    "email": "marcos1234@gmail.com",
    "password": "marcos1234"
}



